# Generated by Django 5.0.4 on 2024-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
